### ISSUE TITLE
job executor hammering cimi server

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamJobEngine#17]
The job executor is hammering the cimi server with many rapid requests for a job that doesn't exist. See a portion of the log below. 

The job executor should back off if multiple requests fail and in this case, should probably update its internal state to remove references to this job.

```
2018-03-04 14:31:56,584 INFO  - 404 (2 ms) GET /api/job/dc7437e6-c5bf-43cc-bc1f-64e50361638a [super/ADMIN,ANON,USER,session/8c5dcd17-58f3-42f6-ac42-a8dae63cab15] ?
2018-03-04 14:31:56,595 INFO  - 404 (6 ms) GET /api/job/dc7437e6-c5bf-43cc-bc1f-64e50361638a [super/ADMIN,ANON,USER,session/8c5dcd17-58f3-42f6-ac42-a8dae63cab15] ?
2018-03-04 14:31:56,602 INFO  - 404 (1 ms) GET /api/job/dc7437e6-c5bf-43cc-bc1f-64e50361638a [super/ADMIN,ANON,USER,session/8c5dcd17-58f3-42f6-ac42-a8dae63cab15] ?
2018-03-04 14:31:56,616 INFO  - 404 (2 ms) GET /api/job/dc7437e6-c5bf-43cc-bc1f-64e50361638a [super/ADMIN,ANON,USER,session/8c5dcd17-58f3-42f6-ac42-a8dae63cab15] ?
2018-03-04 14:31:56,634 INFO  - 404 (3 ms) GET /api/job/dc7437e6-c5bf-43cc-bc1f-64e50361638a [super/ADMIN,ANON,USER,session/8c5dcd17-58f3-42f6-ac42-a8dae63cab15] ?
2018-03-04 14:31:56,644 INFO  - 404 (3 ms) GET /api/job/dc7437e6-c5bf-43cc-bc1f-64e50361638a [super/ADMIN,ANON,USER,session/8c5dcd17-58f3-42f6-ac42-a8dae63cab15] ?
2018-03-04 14:31:56,651 INFO  - 404 (3 ms) GET /api/job/dc7437e6-c5bf-43cc-bc1f-64e50361638a [super/ADMIN,ANON,USER,session/8c5dcd17-58f3-42f6-ac42-a8dae63cab15] ?
```

**Comment by loomis** [comment]
Restarting the job executor services does not remove the problem.

**Comment by loomis** [comment]
<img width="292" alt="response rates by HTTP status category" src="https://user-images.githubusercontent.com/490506/36946797-c631eb0a-1fc2-11e8-9b0f-7c433bf6340f.png">

This is the number of responses **per second**!

**Comment by loomis** [comment]
The system log (messages) is filled with this traceback. 

```
Mar  6 06:34:40 machine761e9e6c-3be9-4770-880b-589e8d2d9083 job_executor.py: ERROR:slipstream.job.executor.Executor:Fatal error when trying to handle job "job/dc7437e6-c5bf-43cc-bc1f-64e50361638a"
Mar  6 06:34:40 machine761e9e6c-3be9-4770-880b-589e8d2d9083 job_executor.py: Traceback (most recent call last):
Mar  6 06:34:40 machine761e9e6c-3be9-4770-880b-589e8d2d9083 job_executor.py: File "/usr/lib/python2.7/site-packages/slipstream/job/executor.py", line 38, in _process_jobs
Mar  6 06:34:40 machine761e9e6c-3be9-4770-880b-589e8d2d9083 job_executor.py: job = Job(self.ss_api, job_uri)
Mar  6 06:34:40 machine761e9e6c-3be9-4770-880b-589e8d2d9083 job_executor.py: File "/usr/lib/python2.7/site-packages/slipstream/job/job.py", line 19, in __init__
Mar  6 06:34:40 machine761e9e6c-3be9-4770-880b-589e8d2d9083 job_executor.py: cimi_job = self.ss_api.cimi_get(job_uri).json
Mar  6 06:34:40 machine761e9e6c-3be9-4770-880b-589e8d2d9083 job_executor.py: File "/usr/lib/python2.7/site-packages/slipstream/api/api.py", line 563, in cimi_get
Mar  6 06:34:40 machine761e9e6c-3be9-4770-880b-589e8d2d9083 job_executor.py: resp_json = self._cimi_get(resource_id=resource_id)
Mar  6 06:34:40 machine761e9e6c-3be9-4770-880b-589e8d2d9083 job_executor.py: File "/usr/lib/python2.7/site-packages/slipstream/api/api.py", line 542, in _cimi_get
Mar  6 06:34:40 machine761e9e6c-3be9-4770-880b-589e8d2d9083 job_executor.py: return self._cimi_request('GET', uri, params=params)
Mar  6 06:34:40 machine761e9e6c-3be9-4770-880b-589e8d2d9083 job_executor.py: File "/usr/lib/python2.7/site-packages/slipstream/api/api.py", line 536, in _cimi_request
Mar  6 06:34:40 machine761e9e6c-3be9-4770-880b-589e8d2d9083 job_executor.py: raise SlipStreamError(message, response)
Mar  6 06:34:40 machine761e9e6c-3be9-4770-880b-589e8d2d9083 job_executor.py: SlipStreamError: job/dc7437e6-c5bf-43cc-bc1f-64e50361638a not found
```

The job engine is clearly getting the 404 error, but then queuing the job again for processing.   To avoid this, consider:

 1. On a 404, fail the job and do not queue it again.
 2. When a job has failed more than _n_ times, fail and do not retry.

In any case, needless processing and load on services need to be avoided.

**Comment by loomis** [comment]
Deployed PR on Nuvla.  Plot after change:

![CIMI Response Rates](https://user-images.githubusercontent.com/490506/37020871-ba435ee4-211d-11e8-9ef5-fcba547974aa.png)

shows that the large number of 404's have been removed. 

The message in `/var/log/messages` was:

```
Mar  6 07:54:40 machine761e9e6c-3be9-4770-880b-589e8d2d9083 job_executor.py: ERROR:slipstream.job.executor.Executor:Fatal error when trying to handle job "job/dc7437e6-c5bf-43cc-bc1f-64e50361638a"
Mar  6 08:03:27 machine761e9e6c-3be9-4770-880b-589e8d2d9083 job_executor.py: WARNING:slipstream.job.executor.Executor:Chef - Job does not exist; removing from queue. Message: job/dc7437e6-c5bf-43cc-bc1f-64e50361638a not found
```

**Comment by 0xbase12** [comment]
Hello, this is due to this line which on error retrieving a job from cimi
will not delete from the  zookeeper queue. This is known and kept like that
to be able to see existing problems with jobs instead of consuming it
silently with a error in the logs.

The problem is I think that when we create a job, during the restart of the
cimi server we put the uuid of the job in zookeeper before putting it in
elasticsearch. And if the restart occurs in the middle we have this
inconsistent situation.

I think that we should the job uuid in zookeeper as last operations. This
will allow to detect old queued jobs in cimi server and manage them with
our specific choices.

For now, if needed on Nuvla to unblock the situation, update the
slipstream/executor.py in site-package to make executor consume the job if
not found queue.consume().
https://github.com/slipstream/SlipStreamJobEngine/blob/master/job/src/slipstream/job/executor.py#L75


Le 6 mars 2018 08:40, "Charles (Cal) Loomis" <notifications@github.com> a
écrit :

**Comment by loomis** [comment]
@0xbase12 Thanks for the information.  I've created a follow-on task (#19) for a more in-depth review of the job handling process and the changes in #18.
