### ISSUE TITLE
analyze job handling

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamJobEngine#19]
Analyze the job handling process between the zookeeper and elasticsearch servers, especially for exceptional cases where there is an inconsistency with the information between them.  In particular, ensure that the process minimizes inconsistencies and that any inconsistencies are identified and dealt with appropriately (e.g. removal from queue, notifications, etc.). 

This is a follow on task from the discussion in #17.  The changes implemented in #18 should be reviewed.

**Comment by 0xbase12** [comment]
The 17th of July at 7pm a cleanup have been done because of 30 blocked jobs and 10 olds.

Checks:
- Normal behavior: 18 July, 9 am
- Normal behavior: 18 July, 9:40 am (restart executor after hot patch collect vms)
- Normal behavior: 19 July, 9:30 am
- Normal behavior: 20 July, 10:45 am

**Comment by schaubl** [comment]
Might be useful as well slipstream/SlipStreamServer#1466
