### ISSUE TITLE
Job action collect_virtual_machines doesn't handle correctly the credentials field

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamJobEngine#29]
When looking at the credentials field of a virtual-machine document generated by the job action collect_virtual_machines ([virtual_machines_collect.py](https://github.com/slipstream/SlipStreamJobEngine/blob/master/job/src/slipstream/job/actions/virtual_machines_collect.py#L39:10)) the number of credentials increase and decrease over time.
It might increase just after the creation of the virtual-machine but should not decrease.

**Comment by schaubl** [comment]
```python

import time
from slipstream.api import Api

api = Api()
api.login_internal('killer', 'nemesys')

while True:
    print len(api.cimi_get('virtual-machine/876b487d-d0ea-3fc3-a56f-76bd64485b9b').credentials)
    time.sleep(2)

```

**Comment by 0xbase12** [comment]
Hot patched Nuvla
