### ISSUE TITLE
Remove virtual machines not updated since more than one hour

### ISSUE THREAD

**Issue by 0xbase12** [slipstream/SlipStreamJobEngine#3]

**Comment by mebster** [comment]
We need to consider NuvlaBox VMs.  If we loose the connection to a box (which we can detect), it would be useful to capture or keep the last known state, but mark it as stale information.

**Comment by 0xbase12** [comment]
Thanks for your good remark

**Comment by 0xbase12** [comment]
Do we need to implement a special logic for NuvlaBoxes? 
```
For vm in (vms not updated since more than one hour):
   if is_nuvlabox_vm and nuvlabox_of_the_vm is not reachable:
      update vm state to 'Unknown'
   else:
      delete vm
```

Is there an impact if we delete the VM and recreate it when the nuvlabox is back?

**Comment by loomis** [comment]
@0xbase12 Is the VM updated every time the `describe-instance` successfully runs; that is, does the "updated" attribute always contain the timestamp for the last time the VM was seen?

**Comment by 0xbase12** [comment]
We edit VM every time describe-instance succeed to set the 'state' attribute of the virtual machine. So 'updated' attribute is updated automatically

**Comment by 0xbase12** [comment]
Done here: https://github.com/slipstream/SlipStreamJobEngine/commit/5daff9fdd76de577700021e76142f0ef40c92ba0

With simple solution delete and if VM reappear for a NB they should be recreated. 
Will add another ticket with the discussion around NuvlaBox case
