### ISSUE TITLE
Cleanup of old sessions

### ISSUE THREAD

**Issue by 0xbase12** [slipstream/SlipStreamJobEngine#4]
https://elasticsearch-py.readthedocs.io/en/master/

**Comment by loomis** [comment]
There is a "delete by query" action that can be used when directly accessing the Elasticsearch API.  This would be the most efficient for session cleanup.

**Comment by 0xbase12** [comment]
This is interesting action, we should use it when we need to delete a large number of documents in ES. For example the cleanup of jobs delete more than 100'000 documents everyday. So as it's done now we should make 100'000 delete requests to ssclj and manually do the paging since the limit of retrieved resources is 10'000.

**Comment by loomis** [comment]
You can also use the bulk actions to avoid having to page through results manually, but the "delete by query" remains the most efficient.

**Comment by 0xbase12** [comment]
There is an issue to get expired session with ES query. 
In fact the date format of expiry field  looks like this (`expiry=Tue, 19 Sep 2017 12:31:57 UTC`).

This date format is mapped automatically by ES to keyword type! This is an issue because AFAIK we can't search keywords like we do for dates. 
```
indices.get_field_mapping(index='resources-index', fields='expiry')

{u'resources-index': {u'mappings': {u'credential': {u'expiry': {u'mapping': {u'expiry': {u'type': u'keyword'}}, u'full_name': u'expiry'}}, u'session': {u'expiry': {u'mapping': {u'expiry': {u'type': u'keyword'}}, u'full_name': u'expiry'}}}}}

```

We can't consider changing the mapping directly in ES because new install of SS will have the same issue.
